### ISSUE TITLE
LogLevel

### ISSUE THREAD

**Issue by jmiglietta-inc** [net-commons/common-logging#47]
Can we change LogLevel into a bit flag enum?  That way it would be nice to log specific levels as a group instead of one, all, or none.  It is a simple thing to do and would provide a great benefit.

**Comment by DannyVarod** [comment]
Since the log levels are ordered like so: trace < debug < info < warn < error < fatal, you can easily filter like so:

if ((int)logLevel <= (int)LogLevel.Debug) { ... }
if ((int)logLevel >= (int)LogLevel.Info && (int)logLevel <= (int)LogLevel.Warn) { ... }
if ((int)logLevel >= (int)LogLevel.Error) { ... }

Changing the enum to flags, would require change of the values (from 0, 1, 2, 3, 4, ...) to (1, 2, 4, 8, 16, ...) breaking the contracts.

**Comment by sbohlen** [comment]
@DannyVarod 

I'm curious: wouldn't your cast-and-compare-underlying-values scenarios still work the same even if the underlying values were effectively increased to become flag-able values?

So long as we maintained the relationship of trace < debug < info < warn < error < fatal with the new flag-based integer values, I'm thinking that we'd not actually be breaking anything other than any existing code that explicitly tests for the present underlying integer value along the lines of the following...

```c-sharp
if (logLevel == 2) {...};
```
...which is bad form to be avoided when consuming enums anyway :)

Thoughts --?

**Comment by jhmiglietta-inc** [comment]
I think it would certainly still work.  The flag-based values are still in the same relative order; thereby maintaining the original logic.  The the added flexibility of being able to do a bit-wise test for each of the logging levels allows for complete independence between what is logged at each of the logging levels if the implementor so chooses.  

As you point out clients/consumers should not be using the underlying enum values directly, and therefore no contract is broken if those values are changed.  As with the internals of an implementation, as long as the contract remains the same nothing is broken; in this case the names of the enum values and the value order are the contract - not the values themselves.

**Comment by sbohlen** [comment]
Resolved in https://github.com/net-commons/common-logging/commit/1cae7d9f44f5c31cb764e5f5e206b30a51037924

**Comment by DannyVarod** [comment]
@sbohlen Changing the values to Flag values in the same order should be OK if no one is serializing this enum via WCF or to a DB. I do not know if this is a fair assumption or not.
Also, I still don't see why this feature is needed - what can't be done with "<", "<=", ">", ">=" comparisons?

**Comment by sbohlen** [comment]
I suppose its an interesting question whether inability to deserialize a prior version to the next version represents a "breaking change" or not.  Is round-trip serialization a compatibility contract/expectation across non-major versions?

I suppose in a sense it could be considered as such since the usual meaning of "breaking change" is in re: the public API.

Although its also the case that all too many 3rd-party serializers actually take a dependency on the privates of serialization subjects, so in that sense even a *private* breaking change could potentially break round-trip cross-version serialization.

All this leads me to conclude that while you're right that this would break serialization expectations across versions, I also admit that if users have objects persisted in an older version, attempts to massage deserialization to newer versions is probably the responsibility of the consumer rather than our framework.

Re: whether this feature is per se necessary, I agree it's not, but it is helpful to me able to bitwise OR them together to test for multiple combinations of levels in a more concise manner...

-----Original Message-----

**Comment by DannyVarod** [comment]
I noticed a while back that the values were indeed changed in a minor version and updating Common.Logging did break all existing code that wasn't specifically recompiled to use the new values.
